services:
  mysql:
    image: mysql:8.0
    container_name: mysql-provider
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: provider_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3315:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
